# Generated by Django 5.1 on 2024-08-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, help_text='Введите фото', null=True, upload_to='images', verbose_name='Фото клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('product', models.CharField(max_length=100, verbose_name='Товар')),
                ('category', models.CharField(choices=[('Процессоры', 'Процессоры'), ('Материнские платы', 'Материнские платы'), ('Видеокарты', 'Видеокарты'), ('Оперативная память', 'Оперативная память'), ('SSD-диски', 'SSD-диски'), ('HDD-диски', 'HDD-диски'), ('Блоки питания>', 'Блоки питания')], max_length=50, verbose_name='Категория')),
                ('photo', models.ImageField(blank=True, help_text='Введите фото', null=True, upload_to='images', verbose_name='Фото товара')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('Поступил', 'Поступил'), ('Выполняется', 'Выполняется'), ('Закрыт', 'Закрыт')], max_length=50, verbose_name='Статус')),
                ('completed', models.BooleanField(default=False, verbose_name='Заказ завершен')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='base_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
